# Generated by Django 5.0.6 on 2024-06-30 15:49

import rules.contrib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='IncomeItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Создан'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Изменен'),
                ),
                (
                    'name',
                    models.CharField(max_length=255, verbose_name='название'),
                ),
                (
                    'icon',
                    models.ImageField(
                        null=True, upload_to='farm_items', verbose_name='иконка'
                    ),
                ),
                (
                    'base_price',
                    models.IntegerField(verbose_name='базовая цена'),
                ),
                (
                    'base_income',
                    models.IntegerField(verbose_name='базовый доход в секунду'),
                ),
                (
                    'income_multiplier',
                    models.FloatField(
                        default=1.0, verbose_name='множитель дохода'
                    ),
                ),
                (
                    'price_multiplier',
                    models.FloatField(
                        default=1.0, verbose_name='множитель цены'
                    ),
                ),
                (
                    'visible',
                    models.BooleanField(
                        default=False, verbose_name='видимость'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Предмет для дохода',
                'verbose_name_plural': 'Предметы для дохода',
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Создан'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Изменен'),
                ),
                (
                    'name',
                    models.TextField(max_length=255, verbose_name='Название'),
                ),
                ('reward', models.IntegerField(verbose_name='Награда')),
                (
                    'visible',
                    models.BooleanField(
                        default=False, verbose_name='Достпность для просмотра'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UserIncomeItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Создан'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Изменен'),
                ),
                (
                    'level',
                    models.IntegerField(default=1, verbose_name='количество'),
                ),
            ],
            options={
                'verbose_name': 'Пользовательский предмет для дохода',
                'verbose_name_plural': 'Пользовательские предметы для дохода',
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
