# Generated by Django 5.0.6 on 2024-06-30 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='users_claimed',
            field=models.ManyToManyField(
                related_name='promos_claimed',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Пользователи, которые промо',
            ),
        ),
        migrations.AddField(
            model_name='userincomeitem',
            name='item',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user_income_items',
                to='game.incomeitem',
                verbose_name='предмет для дохода',
            ),
        ),
        migrations.AddField(
            model_name='userincomeitem',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user_income_items',
                to=settings.AUTH_USER_MODEL,
                verbose_name='пользователь',
            ),
        ),
        migrations.AddField(
            model_name='incomeitem',
            name='user_items',
            field=models.ManyToManyField(
                through='game.UserIncomeItem',
                to=settings.AUTH_USER_MODEL,
                verbose_name='пользовательские предметы',
            ),
        ),
        migrations.AddConstraint(
            model_name='userincomeitem',
            constraint=models.UniqueConstraint(
                fields=('user', 'item'), name='unique_user_item'
            ),
        ),
    ]
